[package]
name = "json-lsp-hz"
version = "0.1.0"
edition = "2021"
author = "shnarazk@github.com"

[dependencies]
lsp-types = "^0.94"
serde_json = "^1.0"
tower-lsp = "^0.20"
tokio = { version = "1", features = ["full"] }
